### ISSUE TITLE
Documentation for parameters color range seems wrong

### ISSUE THREAD

**Issue by Soreine** [raulriera/react-native-window-tint-color#2]
The library makes it look like you need to provide RGB as three 0-255 values, like `WindowTintColor.setTintColor(255, 0, 0);` but actually, values between 0-1 are expected.

So you would write something like `WindowTintColor.setTintColor(1.0, 0.5, 0)`

**Comment by raulriera** [comment]
Ah! you are correct, I had the code that was diving by 255 the passed values. I will update that! thanks
